services:
  thatkitebot:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
      - redis_cache

    volumes:
      - ./thatkitebot/:/app/thatkitebot:Z
      - ./data/:/app/data/:Z
      - ./trains/:/app/data/trains/:Z
      - ./.git/:/app/.git:Z
      - ./logs/:/var/log/thatkitebot/:Z
      - ./config/policy.xml:/etc/ImageMagick-6/policy.xml:Z
    restart:  "no"
    environment:
      - PYTHONUNBUFFERED=1
      - KITEBOT_DEBUG=0
      - DISCORD_DEBUG=0
    command: bash -c "cd /app/ && /app/thatkitebot-venv/bin/python3 -m thatkitebot"

  redis:
    container_name: thatkitebot_redis
    volumes:
      - ./data/redis:/data:Z
    image: "valkey/valkey:alpine"
    entrypoint: valkey-server --appendonly yes --hz 50

  redis_cache:
    container_name: thatkitebot_redis_cache
    image: "valkey/valkey:alpine"
    entrypoint: valkey-server --save "" --appendonly no --hz 50
