services:
  thatkitebot:
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    links:
      - "redis:thatkitebot_redis"
      - "redis_cache:thatkitebot_redis_cache"
    ports:
      - 5678:5678

    volumes:
      - ./thatkitebot/:/app/thatkitebot
      - ./data/:/app/data/
      - ./trains/:/app/data/trains/
      - ./.git/:/app/.git
      - ./logs/:/var/log/thatkitebot/
    restart:  "no"
    environment:
      - PYTHONUNBUFFERED=1
      - KITEBOT_DEBUG=1
      - DISCORD_DEBUG=0

    command: ["bash", "-c", "cd /app/ && thatkitebot-venv/bin/python3 -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m thatkitebot"]    

  redis:
    container_name: thatkitebot_redis
    volumes:
      - ./data/redis:/data
    image: "valkey/valkey:alpine"
    entrypoint: valkey-server --appendonly yes --hz 50

  redis_cache:
    container_name: thatkitebot_redis_cache
    image: "valkey/valkey:alpine"
    entrypoint: valkey-server --save "" --appendonly no --hz 50
