# this determines the load order of the cogs
ENABLED_EXTENSIONS = [
    "thatkitebot.cogs.listenercog",
    "thatkitebot.cogs.starboard",
    "thatkitebot.cogs.repost",
    "thatkitebot.cogs.moderation",
    "thatkitebot.cogs.settings_new",
    "thatkitebot.cogs.electroslash",
    "thatkitebot.cogs.detrack",
    "thatkitebot.cogs.imagecog",
    "thatkitebot.cogs.uwucog",
    "thatkitebot.cogs.help",
    "thatkitebot.cogs.chemistry",
#    "thatkitebot.cogs.music",
    "thatkitebot.cogs.info",
    "thatkitebot.cogs.bookmark",
    "thatkitebot.cogs.sudocog",
    "thatkitebot.cogs.settings",
    "thatkitebot.cogs.unitscog",
    "thatkitebot.cogs.utilities",
    "thatkitebot.cogs.welcomecog",
    "thatkitebot.cogs.laser",
    "thatkitebot.cogs.electronics",
    "thatkitebot.cogs.funstuffcog",
]