ENABLED_EXTENSIONS = [
    "thatkitebot.cogs.listenercog",
    "thatkitebot.cogs.funstuffcog",
    "thatkitebot.cogs.imagecog",
    "thatkitebot.cogs.nsfwcog",
    "thatkitebot.cogs.uwucog",
    "thatkitebot.cogs.utilities",
    "thatkitebot.cogs.settings",
    "thatkitebot.cogs.settings_new",
    "thatkitebot.cogs.help",
    "thatkitebot.cogs.chemistry",
#    "thatkitebot.cogs.electronics",
#    "thatkitebot.cogs.electroslash",
    "thatkitebot.cogs.laser",
    "thatkitebot.cogs.welcomecog",
    "thatkitebot.cogs.repost",
    "thatkitebot.cogs.starboard",
    "thatkitebot.cogs.music",
    "thatkitebot.cogs.info",
    "thatkitebot.cogs.detrack",
    "thatkitebot.cogs.bookmark",
    "thatkitebot.cogs.sudocog",
]